######################################################################
# Automatically generated by qmake (2.01a) ?? 20. ??? 12:41:55 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += regexpdialog.h
SOURCES += main.cpp regexpdialog.cpp
