######################################################################
# Automatically generated by qmake (2.01a) ?? 19. ??? 21:45:41 2008
######################################################################

TEMPLATE = app
TARGET = tsreader
DEPENDPATH += .
INCLUDEPATH += .
CONFIG  += qt
CONFIG  += console
QT      += xml
QT      -= gui

# Input
HEADERS +=	tsreader.h \
			dbconnect.h \
			ticket.h
SOURCES +=	main.cpp
