######################################################################
# Automatically generated by qmake (2.01a) ?? 19. ??? 21:45:41 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui
CONFIG += console

# Input


SOURCES  += main.cpp